// <auto-generated />
namespace ProductCatalog.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WithoutEquipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WithoutEquipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201812170510193_WithoutEquipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
